### ISSUE TITLE
[Feature request] Possibility to copy yml path

### ISSUE THREAD

**Issue by bunufi** [jwheur/yaml-helper#1]
Nicely done with the atom plug in @jwheur. Thanks! 
It would be really cool to have an option to copy current yml path when clicking on it on the status bar.
Exactly the same way as it is done with file path. 
That would be stellar!

**Comment by jwheur** [comment]
@bunufi Good idea, I've added that copy button and copy buttons next to the list results as well on the latest update, thanks for the suggestion!
